# TODO see this https://blog.ionelmc.ro/2014/05/25/python-packaging/
language: cpp
sudo: required
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # PyPy versions
  - "pypy3"
install:
  # command to install dependencies
  - sudo apt-get update
  #- sudo apt-get install -y libffi-dev libssl-dev
  - sudo apt-get install -y python3-pip
  - python3 --version
  - pip3 --version
  #- pip3 install pyopenssl ndg-httpsclient pyasn1
  - pip3 install -r requirements_test.txt .
# command to run tests
script: ./setup.py nosetests
after_success:
  codecov
