# TODO see this https://blog.ionelmc.ro/2014/05/25/python-packaging/
# TODO see https://github.com/google/googletest/blob/master/.travis.yml
# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

language: python
sudo: required
dist: trusty # python3-pip requires 14.04+
python:
  - "3.7-dev"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
#  # PyPy versions
#  - "pypy3"
install:
  # command to install dependencies
  - sudo apt-get update
  - sudo apt-get install -y python3-pip python3-dev
  - sudo apt-get install -y cmake build-essential
  - python3 -V
  - pip3 -V
  - pip3 install -r requirements_test.txt .
  - cmake --version
  - which cc && cc --version
  - which c++ && c++ --version
  - which g++ && (g++ -dumpversion ; g++ --version)
  - which clang++ && (clang++ -dumpversion ; clang++ --version)
# command to run tests
script: env PYTHONPATH=src python3 -m nose -v --with-id --nocapture
after_success:
  codecov
