language: cpp
sudo: required
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # PyPy versions
  - "pypy3"
install:
  # command to install dependencies
  - pip3 install -r requirements_test.txt .
# command to run tests
script: ./setup.py nosetest
