# TODO see this https://blog.ionelmc.ro/2014/05/25/python-packaging/
language: cpp
sudo: required
dist: trusty # python3-pip requires 14.04+
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # PyPy versions
  - "pypy3"
install:
  # command to install dependencies
  - sudo apt-get update
  - sudo apt-get install -y python3-pip python3-dev
  - sudo apt-get install -y cmake build-essential
  - python3 -V
  - pip3 -V
  - pip3 install -r requirements_test.txt .
  - cmake --version
  - which cc && cc --version
  - which g++ && g++ --version
  - which clang++ && clang++ --version
# command to run tests
script: python3 setup.py nosetests
after_success:
  codecov
