# TODO see this https://blog.ionelmc.ro/2014/05/25/python-packaging/
language: cpp
sudo: required
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # PyPy versions
  - "pypy3"
install:
  # command to install dependencies
  - python3 --version
  - pip --version
  - pip install -r requirements_test.txt .
# command to run tests
script: ./setup.py nosetests
after_success:
  codecov
