# TODO see this https://blog.ionelmc.ro/2014/05/25/python-packaging/
# TODO see https://github.com/google/googletest/blob/master/.travis.yml
# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

language: python

# need to use trusty because python3-pip requires 14.04+
matrix:
  include:

    - os: linux
      dist: trusty
      sudo: required
      python: 3.7-dev
      env: PY=3.7

    - os: linux
      dist: trusty
      sudo: required
      python: 3.6
      env: PY=3.6

    - os: linux
      dist: trusty
      sudo: required
      python: 3.5
      env: PY=3.5

    - os: linux
      dist: trusty
      sudo: required
      python: 3.4
      env: PY=3.4

    - os: linux
      dist: trusty
      sudo: required
      python: 3.3
      env: PY=3.3

    # OS X tests are *very* slow. enable only one.
    #- os: osx
    #  language: generic
    #  env: PY=3.7 PYENV=3.7-dev

    #- os: osx
    #  language: generic
    #  env: PY=3.6 PYENV=3.6.0

    - os: osx
      language: generic
      env: PY=3.5 PYENV=3.5.0

    #- os: osx
    #  language: generic
    #  env: PY=3.4 PYENV=3.4.0

    #- os: osx
    #  language: generic
    #  env: PY=3.3 PYENV=3.3.0

install:
  # command to install dependencies
  - chmod a+x ./.ci/travis_install.sh ; ./.ci/travis_install.sh

# command to run tests
script: chmod a+x ./.ci/travis_test.sh ; ./.ci/travis_test.sh

#after_success:
#  codecov
